const placeholderChapter = (chapter) => {
  const day = String(chapter).padStart(2, '0');

  return {
    chapter,
    date: `2026-05-${day}`,
    title: chapter === 17 ? 'Birthday Queen Day' : `Chapter ${chapter}: Page ${chapter}`,
    body: [
      `This is placeholder text for chapter ${chapter} of Bae's Anatomy.`,
      'Replace this with the real story entry when it is ready. Each chapter unlocks on the same day as its matching scrapbook page.',
      'Keep chapters short enough to feel good on a phone, like a page from a tiny book made just for Jessica.',
    ],
  };
};

export const storyChapters = [
  {
    chapter: 1,
    date: '2026-05-01',
    title: 'Chapter 1: The Calm Within the Storm',
    body: [
      'Panic is in the air. Celeste is sobbing louder as precious seconds are going by. Nathaniel is saying all the wrong words trying to calm Celeste down. Christopher is looking aimlessly around trying to find the forceps that are evading him even though they are right in front of his face. And Jon, ummm, he thinks he is here just for his handsome looks. My resolve is unshaken as I silently mouth the process. "Breathe. Assess. Pressure. Inspect. Approximate." It keeps me focused and my mind on the task. I am the calm island in the storm of chaos around me.',
      'Celeste has been crying uncontrollably in the corner since they arrived. She brought her husband in because he was trampled by an out of control carriage. He moved her out the way to keep her from being hit first. The incident has left poor Treyveon with a severely fractured leg and a large open wound on his abdomen. Celeste was able to help the big lug to my care facility a few blocks away. Which is as fortunate as can be in this situation.',
      'Blood JUMPS from the wound and startles Nathaniel, which drives Celeste into an even deeper panic. Jon grabs the tools, hands them to me, and smiles bright...mission accomplished like he is really helping. I continue to mouth the process, I zone in, I lower my heart rate, I center myself and reach to the God given grace within me. The well of grace I normally feel has been slippery lately. It has caused a bit of unease within me. But I cannot worry about that now. This wound cannot wait.',
      'I dig within grasping for my grace, the temperature in the room feels HIGH. I glance at Jon who tries to read my mind. And like magic, he heads to the thermostat. I do not have much time, Treyveon has lost a lot of blood already but I got this. I dig even deeper and feel the strands of my grace. I lend them to Treyveon, slowly closing the rupture that has hit a few internal organs. Celeste\'s mouth falls open but she is silent for the first time and she witnesses the process. The grace was barely enough to get him patched up internally. Steam slowly arises from the wound as Treyveon lets out a small groan of relief.',
      'The bleeding lessens. Jon takes over and begins stitching the skin. Immediate crisis averted. Treyveon will live. Our facility is low on many supplies so we do what we can with patching the flesh and getting his leg in a brace. Celeste and Treyveon will have to venture into town to get the leg fully casted but the hard part is over. They can begin to heal mentally as well as physically. We graciously accept what little credits they have to offer. Times are tough for everyone. The whole village is struggling. Restoration Care is struggling but by His grace...we will find a way.',
      'I walk them to the door and wave as they walk away. The cool evening air feels good and provides a moment of peace and stillness in contrast to the tense and fiery moments before. I enjoy this moment of calm before it is interrupted by the sound of glass shattering. Yup, that sounds about right.',
    ],
  },
  {
    chapter: 2,
    date: '2026-05-02',
    title: 'Chapter 2: Blue Dusk and Broken Vials',
    body: [
      '“WHY DID YOU BUMP INTO ME CHRISTOPHER!?” Nathaniel shouts at Christopher who responds sarcastically “IT’S FIINNNEEEEE“. I turn around and see Nathaniel and Christopher fussing at each other and standing over lab vials.',
      'Ahh the joy of having your two teenage sons help out around the facility. It was cute at first when they were younger. They still had the childlike determination to help and follow instructions. Newfound muscles to lift things and help build a new section of the facility. And then teenage self realization hits and their moods, motivations, and energies changed. They are no longer my babies but soon to be adults ready to leave the nest. It is bittersweet as a mother to see the seeds you planted grow but also it might be time for them to leave and stop ruining my practice!',
      '“Nathaniel clean that up now! Christopher, if you do not have that inventory list to me by the end of the night, you are not going to that Blue Dusk,” I say sternly as they groan in their displeasure. Their shenanigans are becoming too much. We are already low on supplies and we cannot waste what little we have right now.',
      'Everything is low right now. Low on energy, grace, time, credits, and any sign that the rest of the evening will be enjoyable. We have too much going on and not enough of anything. Barring any emergencies, Treyveon is the last patient I have the desire or grace to see tonight. The boys and I tidy up the front. We all had dropped everything as soon as Celeste burst in earlier. They chat about their plans at Blue Dusk. What they will wear and who they will talk to.',
      'I miss going to Blue Dusk. Being young and full of hormones, anxiety, and energy. Choosing which light blue to wear. The awkward exchanges between potential suitors as you would promenade around the plateau. Jumping into the Rosa River with Jon.',
      '“You know I met your dad at Blue Dusk” I say to the boys with a smile. The look of disgust on the boy’s face is a brief moment of joy.',
      '“Speaking of, where is your Dad?” I ask them as I finish organizing Nathaniel’s reception desk. The look of obliviousness on their faces take me right to the edge. Getting teens to care about anything other than immediate self is Samson-esque task. And I do not have the strength in me right now.',
      'I head to the back, the boys brought me to the edge and Jon is here with the final push!',
      '“WAKE UP!” I yell uncontrollably. Jon’s eyes shoot open and he frantically starts moving.',
      '“HOW ARE YOU ASLEEP!?” I blurt out with a mix of confusion and astonishment.',
      '“I wasn’t asleep, I was just making sure the waiting chair was good. Poor Celeste, had made a mess over here.” Jon wakes up like he was not just fast asleep. Our operating room is disorganized and half clean. Jon did a decent job at cleaning up the fluid mess but he is far from getting it back to a reset point.',
      '“I got this! I will finish up down here then I will cook up some poultry and rice. Then we can enjoy the rest of the evening.” He says as he comes over and tries to kiss and hug me. I move away, sweet nothings will not get Restoration Care ready for tomorrow.',
      'Jon resumes organizing the operating room and I begin straightening the chairs where Celeste and Nathaniel were sitting doing the operation. I sit down for a second just to color my thoughts. Jon smirks and lets out a quick chuckle. I shoot him a menacing glance because nothing is funny right now. I take a deep breath to reset. And then another. “BREATHE” I say to myself.',
      'One breath at a time.',
      'One moment at a time.',
      'One step at a time.',
      'I try to assess the situation but I can not focus. I just breathe.',
      'zzzzzzzzzzzzzzzzzzzzzz',
    ],
  },
  {
    chapter: 3,
    date: '2026-05-03',
    title: 'Chapter 3: Ray Marrow Spectacles',
    body: [
      '“Feet.” I stir back to consciousness. “FEET!” Jon says again motioning with the mopper stick.',
      '“I wasn’t sleep.” I say as I lift my feet.',
      '“I don’t blame you. That chair is COMFORTABLE plus it has been a long day.” he smirks as he continues.',
      '“That chair too comfortable. Where we buy that at?” I say as I get up and look around the room. I did not doubt Jon’s cleaning abilities or effort. Just finishing the job is another story. He can be a good husband, sometimes. For the half he does not get done, I am there. And vice versa. I guess we complete each other.',
      '“You are tired! Go upstairs, hygiene, and watch a few illusions. I got supper covered.” He laughs and continues his task.',
      '“I don’t want to watch any illusions tonight.” I grumble as I start to walk off. Meditation and prayer will help me reconnect with my grace. Observing the illusions move in the gray box does not. They are entertaining though.',
      'The rate at which new technologies are appearing is alarming. The salesmen speak of revolution but they provide a mild convenience at best. At worst, they are a money and time sink.',
      'I turn back and look at Jon before leaving the room. He has done a good job resetting the operating room. He does a little shimmy, then looks up and winks as if he can feel me thinking about him. That man cannot wink with one eye. It looks like it pains the other half of his face.',
      '“Side note, I will take Christopher to town tomorrow to get supplies after I finish the Warden’s supply shed. I will use the credits to get everything.” Jon says as he looks through the sparse cabinets.',
      '“No, I will go with him. I am closing early. I need to see Silvie, she wants me to look at a few things. She has to get a few of her girls ready for Blue Dusk. I am headed up.” I respond as I leave the room.',
      'As I go to lock the front door, I see a lady and two gentlemen unloading a carriage with boxes. I make eye contact with the lady who then speeds towards me.',
      '“Chioma Michel’le I presume?” The lady inquires and stares blankly. She is obviously not from the village. We do not refer to those that have been blessed with His grace as Chioma here but it is the formal title. I debate if this person warrants a response at all.',
      'Restoration Care is effectively closed for the evening and strangers at your doorstep at this time is rarely a good thing. Especially when the strangers are as rude as these are. But recent alertness and curiosity have gotten the best of me.',
      '“Speak plainly, clearly, and swiftly. Who are you and what business do you desire with the Chioma of the village?” I entertain with the same tone she provided.',
      '“Mayhaps we started on the wrong foot. I am Delphine of Bayou Medical Technologies. Due to dusk eluding us, Michel’le, I will make this quick.” She grabs a bag from one of the boxes that one of the gentlemen had brought forward.',
      '“The medical practice is changing. The need for you Chioma puts a strain on everyone. There are few of you and many of the ones in need. We have new tools and technologies that are helping with medical care. Allow you to help more people. Make more money and maybe even go beyond this podunk town. These tools can ease the burden on you.” She says as she stares me directly in the eye.',
      '“I offer a gift, a few elixirs and a tool that we offer. The Ray Marrow spectacles. They allow you to see bone through the skin. A brief sample of the technologies that we have coming down the pipeline. Blue Hill Medical up yonder is growing fast. So I KNOW, WE WILL TALK FURTHER at the Blue Dusk gathering. Did this meet your..how did you put it…plainly, clearly, and”',
      '“NOT SWIFT ENOUGH! Good night!” Jon barges in as he steps in front of me and ushers the strangers off the property. I could not shake the feeling that I was having about them. I could not pinpoint it for a variety of reasons, be it fatigue, being low on grace, or hunger.',
      'I head upstairs to our private dwelling above the care facility on the first level. I prepare for the days ahead. I fiddle with the Ray spectacles. These would be convenient. I could have maybe saved some grace when mending Treyveon’s leg earlier using these. Even if I did not have the proper brace or supplies. I ponder the tools and toss them back in the bag.',
      'As soon as I do, I feel Jon’s arms wrap around me. It feels good to be in his embrace. We stand in this moment. Here. Right now. Present. We breathe. Not worried about the uncertainty of tomorrow. But together, me, Jon, and the boys. We will take it head on. Together.',
    ],
  },
  {
    chapter: 4,
    date: '2026-05-04',
    title: 'Chapter 4: The Flyer',
    body: [
      'The next morning is methodical. Prayer, meditation, patients. Checkups and appointments. The business of Restoration Care is enjoyable. We serve God and we serve the community. Hillpoint is a small village not far outside of town. Few end up here on purpose. Even fewer end up staying long term. The families that populate the village have been here for generations. So you know most of the faces around the village. Everyone\'s business would end up in the wind faster than a toddler holding something they should not have.',
      'Like my last few patients that I will see before I close. Old Gerald here is in for an abnormal stomach ache. Word in the wind says he might be running around on his old lady. And his lady Ernestine is handy with potions and brews and knowing a thing or two about putting things in food that may put your stomach in knots. I give him a vial of medicine and tell him to lay off the cholesterol and the ladies around town.',
      'Sister Lakethia is in with her son and daughter. Her son sprained his ankle playing ball. She uses this as an excuse to talk and gossip. Jon comes in as I am tending to the boy. He spends the mornings repairing, building, or whatever odd job that might be needed around town for credits before helping in the practice in the afternoons.',
      'Jon and Nathaniel will head to the hills for whatever the menfolk do up there, while Christopher and I will head to the dock to catch a ferry into town for supplies.',
      'I struggle to apply the balm and wrap Jrue\'s ankle. He and Christopher are glued to the illusion on the opposite wall we are facing. It puts his body in a weird position to tend to him. Sister Lakethia helps twist Jrue in position and mentions that Blue Hill Medical has been putting flyers all over town for their new gizmos and technology that can treat anything from the Low Lung Cough to even fast casting broken limbs. And that even members of our Church were curious about going. I remind her that while I am the only Chioma in the village and cannot tend to everyone, whatever technology and gizmotronics they have could not replace everything that the Favored do. We all have our place in the world. I am not here by mistake. I know and understand my purpose here in Hillpoint.',
      'We talk about the excitement of Blue Dusk for the young people. This will be her daughter\'s first cycle to promenade. Many from the church will have young people that will debut this year. It is all the energy at the church.',
      'I instruct Christopher to get ready as we are about to head out. He is still distracted by the illusion coming from the gray box. I repeat it sternly and he pops up with his head on a swivel confused and lost to the world. Lakethia\'s daughter Jasia has been chatting Nathaniel up at the front this entire time. I can tell when Nathaniel is struggling for words.',
      '"I can\'t wait to see you at Blue, Nathaniel," Jasia says bashfully awaiting Nathaniel to speak. I do not know if he has said a word the entire time.',
      '"Ummm, me and my Dad are building something on the hill," Nathaniel blurts out awkwardly.',
      '"Oh, okay." Jasia responds as she slowly turns to follow her mom and brother out of the building.',
      'Jon shakes his head and puts his arm around Nathaniel\'s shoulder as they head to the back. Christopher returns with his pack ready to go. I grab my pack and we head out. We walk through the village waving and greeting neighbors as we make our way to the dock.',
      'The dock market has a bustle to it that the rest of the village does not have. The river that curves and twists through Hillpoint splits it into two distinct areas. The farmlands to the south and the steep hills on the north. The dock, market, and causeway serve as The Nexus. The connection and heartbeat of the village.',
      'We make our way to the ferry and get in queue. Kids play in the vicinity, teens and their PDA, the adults move and work about. A child with an echophone is yelling and promoting the news. He blares out about the ball game scores, a scandal with the Constable, Blue Dusk, the Hillpoint Fair, and other things.',
      'A gentleman comes rushing along passing out flyers to everyone in line. "TAKE THIS, TAKE THIS!" he says as he stuffs a flyer into everyone\'s hand. I walk onto the ferry and the horn sounds. The ferry slowly departs. I look around and everyone is in a commotion over the flyer. The flyer states: COME TO BLUE HILL MEDICAL! THE FUTURE OF MEDICINE IS HERE TODAY! I look up and the gentleman is staring and smiling directly at me.',
    ],
  },
  ...Array.from({ length: 13 }, (_, index) => placeholderChapter(index + 5)),
];
